server.port=${SERVER_PORT:8080}
spring.application.name=${SPRING_APPLICATION_NAME:webhook-retry-engine}

spring.datasource.url=jdbc:postgresql://localhost:5432/webhook_engine
spring.datasource.username=dev_user
spring.datasource.password=dev_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# Health check logging interval in seconds
health.check.interval=5000
