CREATE TABLE webhook (
    id BIGSERIAL PRIMARY KEY,
    url VARCHAR(2048) NOT NULL,
    secret VARCHAR(255) NOT NULL,
    max_retries INT NOT NULL DEFAULT 3,
    retry_policy VARCHAR(50) NOT NULL DEFAULT 'EXPONENTIAL_BACKOFF',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE INDEX idx_webhook_url ON webhook(url);